# CMPT 141 - Arrays
# Topic(s): 2D Arrays


import numpy as np

# example wind farm as a 5x5 grid of turbines
# shows the power generated by the turbine at each location.
turbines = [ [2.5, 2.2, 2.3, 2.5, 2.6],
             [2.6, 2.4, 2.5, 2.5, 2.6],
             [2.7, 2.5, 2.5, 2.6, 2.7],
             [2.7, 2.4, 2.5, 2.5, 2.6],
             [2.2, 2.3, 2.4, 2.5, 2.5] ]

# Part (a) Change the list into a 2D array


# Part (b) Print the dimensions of the wind farm


# Part (c) Print the power output of the first turbine in the fifth row


# Part (d) Print the average power produced by
# the first three turbines in the first row


# Part (e) Print each turbine’s power output, one per line





# things I want to mention for-loop iterator ( use index, use row, use item after reshape)